### ISSUE TITLE
Change target to avoid conflicts

### ISSUE THREAD

**Issue by FranklinYinanDing** [TylerHorth/sbt-restli#10]
Need some more explanation here. And if this is a common practice, consider moving as default value?

**Comment by TylerHorth** [comment]
I've thought about this for a bit, and I think I'm going to take a different approach.

The reason you have to change the target is because I'm building the schema bindings and the client bindings from the same api directory, but from separate projects, and two projects cannot share the same target directory. They cant be build from the same project because there's no way to keep their artifacts separate if you do.

I think that instead of doing it this way which is a bit unintuitive, I'm going to take a similar approach to the RestliModelPlugin, whereby I pass in a reference to the api project through a setting. The downside to this approach is it slightly deviates from the gradle plugin, but I think it's worth it in this case.
