### ISSUE TITLE
sbt-restli first scan

### ISSUE THREAD

**Issue by FranklinYinanDing** [TylerHorth/sbt-restli#2]
- [x] What's the log4j2.xml for?
- [x] Could [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/src/main/scala/sbtrestli/RestliAvroPlugin.scala#L6) just be `sbt._`?
- [x] Instead of [restliAvroGenerate](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliAvroPlugin.scala#L13), I prefer verb-first `generateRestliAvro` for tasks. Same elsewhere.
- [x] Why [here](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliClientPlugin.scala#L73) needs mkdir where avro-plugin doesn't?
- [x] Should [these](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliClientPlugin.scala#L78-L81) be configurable?
- [x] [Default](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliModelPlugin.scala#L21) to backwards?
- [x] [Here](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliModelPlugin.scala#L37) no need to also watch?
- [x] How large is the [summary](https://github.com/TylerHorth/sbt-restli/blob/ef008f61a172198910f320aa54224a481b60e19f/src/main/scala/sbtrestli/RestliModelPlugin.scala#L233)? If too much, then it might be too noisy to be on info level.
- [x] [Here](https://github.com/TylerHorth/sbt-restli/blob/6877b965087a97461f44820855ff28560a71d007/sbt-restli/src/main/scala/sbtrestli/RestliSchemaPlugin.scala#L78) needs some more comment to explain.
- [x] Why [Throwable](https://github.com/TylerHorth/sbt-restli/blob/6877b965087a97461f44820855ff28560a71d007/sbt-restli/src/main/scala/sbtrestli/RestliSchemaPlugin.scala#L94)?

**Comment by TylerHorth** [comment]
> * [x]  What's the log4j2.xml for?

Sbt 1.0 includes log4j and does configuration programatically, which will ignore the configuration from log4j2.xml. For sbt 0.13 and for forked jvm tasks (restliModelGenerate), we must provide log4j configuration ourselves, which comes from log4j2.xml. 

> * [x]  Instead of [restliAvroGenerate](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliAvroPlugin.scala#L13), I prefer verb-first `generateRestliAvro` for tasks. Same elsewhere.

Prefixing plugin tasks and keys with the plugin name is a [sbt best practice](https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Key+naming+convention%3A+Use+prefix). We can subvert this if you think it's a significant ergonomic improvement, but I think there's value in conformity. 

> * [x]  Why [here](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliClientPlugin.scala#L73) needs mkdir where avro-plugin doesn't?

The restli tools (`AvroSchemaGenerator`, `PegasusDataTemplateGenerator`, etc.) create the directories for us already. It's only `RestRequestBuilderGenerator` which doesn't. 

> * [x]  Should [these](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliClientPlugin.scala#L78-L81) be configurable?

I'm not sure if there's much value in it. The `version` and `deprecatedByVersion` parameters are only useful if you want to generate deprecated client bindings (you have to cut deprecated features at some point, right?). The other two parameters, `generateImported` and `generateDataTemplates`, I couldn't think of a use case for, and the gradle plugin doesn't let you configure them either. `generateDataTemplates` is already covered by the `RestliSchemaPlugin`, and `generateImported` generates client bindings for imported projects, when you could just depend on the client bindings of said project.

> * [x]  [Here](https://github.com/TylerHorth/sbt-restli/blob/42761299af6164a828c6fc7c60f331c0fe579ed8/sbt-restli/src/main/scala/sbtrestli/RestliModelPlugin.scala#L37) no need to also watch?

Since rest models are generated from java/scala source files, they are already being watched.

> * [x]  How large is the [summary](https://github.com/TylerHorth/sbt-restli/blob/ef008f61a172198910f320aa54224a481b60e19f/src/main/scala/sbtrestli/RestliModelPlugin.scala#L233)? If too much, then it might be too noisy to be on info level.

The summary prints out the list of compatible changes (or incompatible), and is meant to be user facing. It only prints the first time a change is made, so it shouldn't be too noisy. 

> * [x]  Why [Throwable](https://github.com/TylerHorth/sbt-restli/blob/6877b965087a97461f44820855ff28560a71d007/sbt-restli/src/main/scala/sbtrestli/RestliSchemaPlugin.scala#L94)?

When exceptions go uncaught and do not implement the `FeedbackProvidedException`, sbt prints out the whole exception (including stacktrace) twice. This is of course pretty noisy for exceptions like malformed json or unresolved schema URIs. I'll see if I can narrow this down to a few more specific exceptions, so other errors still get a full stacktrace.

**Comment by FranklinYinanDing** [comment]
Thanks for the explanation!
